### PR TITLE
feat(utils): scale should respects icons w/h ratio

### PR DESCRIPTION
**Pull request by lvjiaxuan**
There are some icons, like logos set, its width is not the same as height.

So I think the scale value should be multiplied by the width and height from `iconToSVG()`.

### CODE REVIEW

**Comment by cyberalien** [comment]
Loader makes icons square by design, other libraries behave differently. Default behaviour should not be changed to avoid breaking stuff for users, but option to render non-square icons is welcome.

I don't have access to computer right now, looking at different this pr seems to change default behavior. If so, pr should be changed to make it an option

**Comment by lvjiaxuan** [comment]
> Loaakes icons square by design, other libraries behave differently. Default behaviour should not be changed to avoid breaking stuff for users, but option to render non-square icons is welcome.
> 
> I don't have access to computer right now, looking at diff this pr seems to change default behavior. If so, pr should be changed to make it an option

I get what you mean. Looks like I've been thinking too little. And I've learned a few from your experience. Thanks!

I will change this PR in the future as personal try. Of course, your change is the one that matter.

**Comment by cyberalien** [comment]
Not implemented yet, but I took some steps to make it possible.

Added 2 more parameters to `customize` callback: icon data and icon name. Icon data can be used to get width/height ratio to set custom props, icon name can be used to check if you are customising correct icon.

**Comment by cyberalien** [comment]
Fixed in `2.1.28`.

I was wrong about default behavior. It was a side-effect of bad `scale` attribute handling. In old version if `scale` was not set, icon had correct width, but with `scale` set it was square. Now it behaves correctly with `scale` option.

**Pull request closed without merging**
