### PR TITLE
feat: customInstall

### PR DESCRIPTION
**Pull request by txp1035**
#199

### CODE REVIEW

**Comment by cyberalien** [comment]
This is a good idea, but I think implementation should be different to be fully backwards compatible.

Instead of adding another option, maybe change existing option to be either boolean or a callback? So `false` = do not install, `true` = use old code, function = use function.

**Comment by txp1035** [comment]
> 这是个好主意，但我认为实现应该有所不同才能完全向后兼容。
> 
> 与其添加另一个选项，不如将现有选项更改为布尔值或回调？所以`false`= 不安装，`true`= 使用旧代码，功能 = 使用功能。

Yes, it's simpler

**Comment by txp1035** [comment]
done

**Comment by cyberalien** [comment]
Thanks a lot! Merged, published new version of Utils.

**Pull request merged**
