### PR TITLE
feat(vue): compatible with SSR

### PR DESCRIPTION
**Pull request by antfu**
In Nuxt, I am trying to find a good solution to render the icons in SSR to avoid the flicking.

I want to call `loadCollection` on server side and use the loaded data to render the SVG icons to SSR. Currently, it passes the icon data fetch with `this.iconMounted`, which is only `true` on the client side. This PR introduces a new `ssr` prop to the component to opt in for the first render and to be compatible with SSR.

### CODE REVIEW

**Comment by cyberalien** [comment]
While this will render icon on server, it will cause a different issue: hydration mismatch for some icons. Component randomises ids used in icon to avoid duplicating them, which will result in different icon content generated on server and browser.

**Comment by cyberalien** [comment]
It is an edge case, which used to give me a lot of headaches with React a while ago, but Vue 3 is very good at handling hydration mismatches, so I guess it is not a big issue.

Might be enough to add notice to docs explaining that hydration mismatches can happen in some edge cases.

**Comment by cyberalien** [comment]
Published as `4.1.2-beta.1` (`@iconify/vue@dev`).

Looks good to me, can you please check if it works as expected in SSR?

**Comment by antfu** [comment]
It works for me already (I was patched it locally) - feel free to ping me if it brings issues to other cases and I am happy to help the Vue integration in general. Thanks!

**Comment by cyberalien** [comment]
Thanks! Published stable version `4.1.2`

**Pull request merged**
