### PR TITLE
feat(next): split modern loader for node and browser support

### PR DESCRIPTION
**Pull request by userquin**
I'll add here some new changes

### CODE REVIEW

**Comment by cyberalien** [comment]
Safeguard in case function is bundled and used in UI?

**Comment by userquin** [comment]
@cyberalien we need to check the dts, I don't know if it would be better to add the correspondong dts for each exports entry, I'll check some docs

**Comment by userquin** [comment]
@cyberalien I added jest configuration for dual test: added 3 new scripts and all the configuration required.

I've removed the type module, it seems jest not working: I'll add also vitest and so you can play with it, but this on weekend.

jasmine tests seems to be working...

**Comment by userquin** [comment]
Also cheked manually that the cjs test is calling the cjs modules and the esm test calling the mjs modules:
- removed the build from test:jest-esm and test:jest-cjs
- added manually a console.log('CJS') and console.log('ESM') to corresponding modules (I use `utils/loader/custom`)
- checked the logs are ok once test:jest-esm and test:jest-cjs finished

**Comment by userquin** [comment]
@cyberalien I'll merge soon next once PR about eslint and prettier merged

**Pull request merged**
