### PR TITLE
Release @iconify/ember 1.0.4

### PR DESCRIPTION
**Pull request by btecu**
Thanks @cyberalien!

### CODE REVIEW

**Comment by cyberalien** [comment]
Not yet. There are some changes to other dependencies that must be pushed first, hopefully within next few hours, then update can be published.

**Comment by btecu** [comment]
@cyberalien Which other dependencies?

**Comment by cyberalien** [comment]
Published update.

By "other dependencies" I meant `@iconify/utils` and `@iconify/core` packages that were modified recently. Changes include different method of handling invalid icons, new build process and new unit tests.

I've rushed release of Ember component, so it is not yet based on new build process, but it contains the rest of changes.

**Comment by btecu** [comment]
> I've rushed release of Ember component, so it is not yet based on new build process, but it contains the rest of changes.

Thanks!

**Pull request closed without merging**
