### PR TITLE
perf(packages/utils): added scope argument in loadCollectionFromFS for load from other packages scope

### PR DESCRIPTION
**Pull request by Scrum**
Hi, thanks for your cool package.

This performance will make it possible to use automatic loading of icons in the package [unplugin-icons](https://github.com/unplugin/unplugin-icons) from arbitrary packages.

I will be glad to receive any comments and suggestions.

**Related:** 
 - https://github.com/unplugin/unplugin-icons/issues/12

### CODE REVIEW

**Comment by cyberalien** [comment]
Thanks for pull request, that is a very useful function!

However it requires some changes:
- Please do not add more dependencies, such as `cpy`. I try to keep dependencies to minimum. Furthermore, that particular dependency has big disclaimer stating that it is basically not maintained, so a definite no to adding it.
- Files used by tests are in `tests/fixtures/`

**Comment by Scrum** [comment]
Thanks for the quick feedback

> Please do not add more dependencies, such as cpy. I try to keep dependencies to minimum. Furthermore, that particular dependency has big disclaimer stating that it is basically not maintained, so a definite no to adding it.

I used this package `cpy` because It is necessary to somehow add the third `package` to `node_modules` from where the modules are imported.

Please tell me if I need to change the tests without using `cpy`, or can I leave it and take it into account in the future?

**Comment by cyberalien** [comment]
It just copies 3 files, which can be done with fs functions without third party package.

**Comment by Scrum** [comment]
> It just copies 3 files, which can be done with fs functions without third party package.

Thank you, I switched to using `fs`

**Comment by cyberalien** [comment]
Thanks a lot!

Merged and published new version of utils.

**Comment by cyberalien** [comment]
Reverted this change.

It is impossible to integrate in Unplugin Icons and causes issues. Different solution is required. See comment in Unplugin Icons PR.

**Pull request merged**
