### PR TITLE
feat: refactor modern loader

### PR DESCRIPTION
**Pull request by userquin**
This PR just moves the `modern` module from `core` package to `utils` package.

On draft, I need to include some more customizations.

### CODE REVIEW

**Comment by userquin** [comment]
The changes included on `unplugin-icons` are not necessary here since we provide the custom transform on `getCustomIcon` and so we can provide transformations.

**Review by cyberalien — APPROVED** [review]
Looks good, though I'd change `return undefined` to just `return` for `loadCollection()` or even change it to `null` for consistency with other functions.

**Comment by userquin** [comment]
some wording, fixing it...

**Comment by cyberalien** [comment]
Looks good. Merged in dev

**Comment by cyberalien** [comment]
Updated code:

- rebased it on `master` branch.
- updated package-lock.json (should figure out how to better deal with it since Lerna doesn't support new format and has been abandoned).
- ran Prettier on new code to fix formatting.

Is this everything you wanted to add so far? If so, I think it would be a good idea to publish new version of utils package.

**Comment by userquin** [comment]
I think it is ok, once released I Will include it on `unocss/preset-icons` and then on `unplugin-icons`

**Comment by cyberalien** [comment]
Published `1.0.21`

**Comment by userquin** [comment]
@cyberalien we should move `mergeIconProps` outside ` packages/utils/src/loader/utils.ts`: I need to review  the `loader` package and do some refactor to allow use it from `node` and `browser` environments.

**Comment by cyberalien** [comment]
Sure.

I'm currently in process of getting rid of Lerna (replacing with NPM workspaces, which is now usable as bug that was preventing me from using it was fixed), which should be ready in few hours unless I'll run into more issues. Maybe apply that change after restructure?

**Comment by userquin** [comment]
ok, I'll wait you

**Comment by cyberalien** [comment]
Sorry, looks like this won't work yet. I've ran into a bug that makes it impossible to have Vue 2 and Vue 3 components in same monorepo. For some reason when running unit tests from Vue 2 workspace, `require('vue')` resolves Vue 3, even though Vue 2 is installed in that workspace. Also Svelte component started magically throwing illogical errors when testing. So this will take a while.

Go ahead and create branch from master without workspaces to update utils.

**Pull request merged**
